import Header from "@/components/Header/Header";
import { Cormorant_Garamond } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Othman Ahmed",
  description: "Generated by create next app",
};

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  style: ["normal", "italic"],
  variable: "--font-editorial",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cormorant.variable}>
      <body className={`antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
