import Header from "@/components/Header/Header";
import { Cormorant_Garamond, DM_Sans } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Othman Ahmed",
  description: "Generated by create next app",
};

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  style: ["normal", "italic"],
  variable: "--font-editorial",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cormorant.variable} ${dmSans.variable}`}>
      <body className={`${dmSans.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
